#!/bin/bash
# Point-LIO 完整修复脚本 - 包含旋转矩阵修正和 IMU 校准

set -e  # 遇到错误立即退出

echo "======================================================================="
echo "Point-LIO 飘移问题完整修复方案"
echo "======================================================================="
echo ""
echo "问题诊断："
echo "  1. ✅ 发现外参旋转矩阵配置错误（pitch 符号反了）"
echo "  2. ⚠️  发现 IMU 角速度零漂约 0.014 rad/s"
echo ""
echo "修复内容："
echo "  1. ✅ 已修正 extrinsic_R 旋转矩阵"
echo "  2. ✅ 已修正 rot_imu.cpp 中的变换角度"
echo "  3. ✅ 已重新编译代码"
echo "  4. ⏳ 待执行 IMU 零漂校准"
echo ""
echo "======================================================================="

cd /home/lab/sentry_ws
source install/setup.bash

echo ""
echo "📝 步骤 1/3: 启动建图系统（在另一个终端）"
echo ""
echo "请在新终端执行以下命令："
echo "----------------------------------------------------------------------"
echo "cd /home/lab/sentry_ws"
echo "source install/setup.bash"
echo "ros2 launch sentry_bringup mapping.launch.py"
echo "----------------------------------------------------------------------"
echo ""
read -p "系统已启动？按 Enter 继续..."

echo ""
echo "📝 步骤 2/3: IMU 零漂校准"
echo ""
echo "⚠️⚠️⚠️ 非常重要 ⚠️⚠️⚠️"
echo "  - 机器人必须完全静止在水平地面上"
echo "  - 不要触碰或移动机器人"
echo "  - 校准需要约 10 秒"
echo ""
read -p "机器人已静止？按 Enter 开始校准..."

echo ""
echo "🔄 正在校准 IMU..."
python3 src/sentry_bringup/scripts/calibrate_imu_bias.py

if [ ! -f "src/sentry_bringup/params/imu_bias_calibration.yaml" ]; then
    echo ""
    echo "❌ 错误：校准失败，未生成校准文件"
    echo ""
    echo "可能原因："
    echo "  - mapping.launch.py 没有运行"
    echo "  - IMU 数据话题 /imu/data 没有发布"
    echo "  - 机器人在移动"
    echo ""
    echo "请检查并重试"
    exit 1
fi

echo ""
echo "✅ IMU 校准完成！"
echo ""

echo "📝 步骤 3/3: 重启建图系统"
echo ""
echo "请执行以下操作："
echo "----------------------------------------------------------------------"
echo "1. 在运行 mapping.launch.py 的终端按 Ctrl+C 停止"
echo "2. 重新运行："
echo "   ros2 launch sentry_bringup mapping.launch.py"
echo ""
echo "3. 观察启动日志，应该看到："
echo "   [mapping.launch.py] 已加载 IMU bias 校准"
echo "   [rot_imu]: IMU transform固定: roll=2.303835, pitch=0.017, yaw=0.000"
echo "   [rot_imu]: IMU bias 补偿已启用"
echo ""
echo "4. 等待 15 秒让系统初始化"
echo "5. 慢速移动开始建图（线速度 < 0.2 m/s）"
echo "----------------------------------------------------------------------"
echo ""

echo "======================================================================="
echo "验证修复效果"
echo "======================================================================="
echo ""
echo "运行以下命令验证 IMU 数据："
echo "  python3 src/sentry_bringup/scripts/check_imu_stability.py"
echo ""
echo "期望结果："
echo "  ✅ 角速度均值 < 0.002 rad/s（从 0.014 降到接近 0）"
echo "  ✅ Z 轴重力 ≈ -9.81 m/s²（向下，用于栅格地图投影）"
echo "  ✅ X, Y 加速度接近 0"
echo ""
echo "======================================================================="
echo ""
echo "🎉 修复完成！"
echo ""
echo "重要提示："
echo "  - 每次断电重启后 IMU 可能需要重新校准"
echo "  - 如果仍有飘移，运行校准脚本重新校准"
echo "  - 详细文档：src/sentry_bringup/PointLIO_飘移完整解决方案.md"
echo ""
